// 41110316 78
// 99924802 - alik
// 126162950 - 1250 78 4ek zzzz
// 193226978 - 300rseti 78 4ek  zzzzz
// 132306089 - 100r 1mesyac 180616peresmotret zzzz
// 219991622 - 300r 3mesyaca peresmotret zzzz
// 145908480 - 100r 1 mesyac 220216 zzzz
// 190008075 - Andrew Kastov 600r78 God 010516
// 318374333 - 200 r 2 modeli 1 mesyac 
// 239382549 - 100 r  model 1 mesyac
// 209676167 - 100 r model 1 mesyac
// 318703032 - 100 r model 1 mesyac 270716
// 214558986 - 100 r model 1 mesyac 280716
// 133720517 - 100 r model 1 mesyac 300716
// 336788038 - 100 r model 1 mesyac 300716
// 353431550 - 100 r model 1 mesyac 310716
// 168121151 - Versuta
// 222505485 - Brittel
// 224175813 - 200 r 2 modeli 1 mesyac 190816
// 160762664 - 100r model 1 mesyac 240816
// 247430095 - 100r model 1 mesyac 250816
// 174649429 - gospodin aleksei
// 161313368 - snim
// 193454280 - 100r model 1 mesyac 310816
// 245326972 - 170916 3mesyaca
// 367648724 - 170916 3mesyaca
// 169426302 - 210916 1 mesyac
// 59816339 - babulka 011016
// 304298086 - 081016 1 mesyac
// 223526951 - 081016 1 mesyac
// 122674675 - 1 mesyac
// 113871125 -161016 ?
// 343364427 - sosik
// TOP DONATER - 421647980
// wallseat - 147822742


"custom_skins"
{
	"kvn"
	{
		"english"
		{
			"models/heroes/rattletrap/rattletrap.vmdl" "model"
			"models/items/rattletrap/forge_warrior_helm/forge_warrior_helm.vmdl" "wearable"
			"models/items/rattletrap/forge_warrior_claw/forge_warrior_claw.vmdl" "wearable"
			"models/items/rattletrap/forge_warrior_rocket_cannon/forge_warrior_rocket_cannon.vmdl" "wearable"
			"models/items/rattletrap/forge_warrior_steam_exoskeleton/forge_warrior_steam_exoskeleton.vmdl" "wearable"
		}
		"russian"
		{
			"models/heroes/rattletrap/rattletrap.vmdl" "model"
			"models/items/rattletrap/forge_warrior_helm/forge_warrior_helm.vmdl" "wearable"
			"models/items/rattletrap/forge_warrior_claw/forge_warrior_claw.vmdl" "wearable"
			"models/items/rattletrap/forge_warrior_rocket_cannon/forge_warrior_rocket_cannon.vmdl" "wearable"
			"models/items/rattletrap/forge_warrior_steam_exoskeleton/forge_warrior_steam_exoskeleton.vmdl" "wearable"
		}
		    "275002088"
    {
      "npc_dota_hero_wisp" "hero"
      "models/items/io/io_ti7/io_ti7.vmdl" "model"
      "particle1" 
      {
        "particle" "particles/econ/items/wisp/wisp_ambient_ti7.vpcf"
        "attach" "PATTACH_OVERHEAD_FOLLOW"
      }
      "particle2" 
      {
        "particle" "particles/econ/items/wisp/wisp_ambient_ti7_trace_glow.vpcf"
        "attach" "PATTACH_POINT_FOLLOW"
      }
      "ACT_DOTA_IDLE" "animation"
    }
		"294826872"
		{
			"npc_dota_hero_nevermore_alt1" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}
		"186777632"
		{
			"npc_dota_hero_legion_commander_alt1" "hero"
			"models/heroes/legion_commander/legion_commander.vmdl" "model"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_shoulder.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_head.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head/stonehall_head.vmdl" "wearable"
			"models/items/legion_commander/legacy_of_the_fallen_legion/legacy_of_the_fallen_legion.vmdl" "wearable"
			"models/items/legion_commander/stonehall_arms/stonehall_arms.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_legs.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl_mg" "1"
			"particle1"
			{
				"particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
			"dualwield" "translate"
		}
		"350506402"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_navi.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
		"364460038"
		{
		"npc_dota_hero_crystal_maiden" "hero" 
"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model" 
"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_head/warden_icewrack_head.vmdl" "wearable" 
"models/items/crystal_maiden/immortal_shoulders/cm_immortal_shoulders.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_staff/warden_icewrack_staff.vmdl" "wearable" 
"models/items/crystal_maiden/crystalline_empress_arms/crystalline_empress_arms.vmdl" "wearable" 

"particle1" 
{ 
"particle" "particles/maiden_freezing_field_casterribbons_arcana1_custom.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient.vpcf" 
"attach" "-1" 
} 


"particle5" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_ball_sparks.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_halo.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient.vpcf" 
"attach" "-1" 
} 

"particle7" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
} 
"particle8" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_ground_ambient.vpcf" 
"attach" "-1" 
} 
"particle9" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle10" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle11" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient.vpcf" 
"attach" "-1" 
} 
"particle12" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle13" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle14" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_d.vpcf" 
"attach" "-1" 
} 
"particle15" 
{ 
"particle" "particles/econ/items/pangolier/pangolier_ti8_immortal/pangolier_ti8_immortal_ambient_hearts.vpcf" 
"attach" "-1" 
} 
"particle16" 
{ 
"particle" "particles/units/heroes/hero_tusk/tusk_frozen_sigil.vpcf" 
"attach" "-1" 
} 

"particle18" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
}
		}
		"132163810"
		{
			"npc_dota_hero_legion_commander_alt1" "hero"
			"models/heroes/legion_commander/legion_commander.vmdl" "model"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_shoulder.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_head.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head/stonehall_head.vmdl" "wearable"
			"models/items/legion_commander/legacy_of_the_fallen_legion/legacy_of_the_fallen_legion.vmdl" "wearable"
			"models/items/legion_commander/stonehall_arms/stonehall_arms.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_legs.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl_mg" "1"
			"particle1"
			{
				"particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
			"dualwield" "translate"
		}
		"213911362"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_liquid.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
		"297739985"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_navi.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
        "133531922"
{
"npc_dota_hero_crystal_maiden" "hero" 
"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model" 
"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_head/warden_icewrack_head.vmdl" "wearable" 
"models/items/crystal_maiden/immortal_shoulders/cm_immortal_shoulders.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_staff/warden_icewrack_staff.vmdl" "wearable" 
"models/items/crystal_maiden/crystalline_empress_arms/crystalline_empress_arms.vmdl" "wearable" 

"particle1" 
{ 
"particle" "particles/maiden_freezing_field_casterribbons_arcana1_custom.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient.vpcf" 
"attach" "-1" 
} 


"particle5" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_ball_sparks.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_halo.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient.vpcf" 
"attach" "-1" 
} 

"particle7" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
} 
"particle8" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_ground_ambient.vpcf" 
"attach" "-1" 
} 
"particle9" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle10" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle11" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient.vpcf" 
"attach" "-1" 
} 
"particle12" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle13" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle14" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_d.vpcf" 
"attach" "-1" 
} 
"particle15" 
{ 
"particle" "particles/econ/items/pangolier/pangolier_ti8_immortal/pangolier_ti8_immortal_ambient_hearts.vpcf" 
"attach" "-1" 
} 
"particle16" 
{ 
"particle" "particles/units/heroes/hero_tusk/tusk_frozen_sigil.vpcf" 
"attach" "-1" 
} 

"particle18" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
}
}
		
		"148967307"
		{
		"npc_dota_hero_crystal_maiden" "hero" 
"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model" 
"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_head/warden_icewrack_head.vmdl" "wearable" 
"models/items/crystal_maiden/immortal_shoulders/cm_immortal_shoulders.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_staff/warden_icewrack_staff.vmdl" "wearable" 
"models/items/crystal_maiden/crystalline_empress_arms/crystalline_empress_arms.vmdl" "wearable" 

"particle1" 
{ 
"particle" "particles/maiden_freezing_field_casterribbons_arcana1_custom.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient.vpcf" 
"attach" "-1" 
} 


"particle5" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_ball_sparks.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_halo.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient.vpcf" 
"attach" "-1" 
} 

"particle7" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
} 
"particle8" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_ground_ambient.vpcf" 
"attach" "-1" 
} 
"particle9" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle10" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle11" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient.vpcf" 
"attach" "-1" 
} 
"particle12" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle13" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle14" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_d.vpcf" 
"attach" "-1" 
} 
"particle15" 
{ 
"particle" "particles/econ/items/pangolier/pangolier_ti8_immortal/pangolier_ti8_immortal_ambient_hearts.vpcf" 
"attach" "-1" 
} 
"particle16" 
{ 
"particle" "particles/units/heroes/hero_tusk/tusk_frozen_sigil.vpcf" 
"attach" "-1" 
} 

"particle18" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
}
		}

		"238499963"
		{
		    "npc_dota_hero_terrorblade_alt1" "hero" 
            "models/heroes/terrorblade/terrorblade.vmdl" "model" 
            "models/heroes/terrorblade/horns_arcana.vmdl" "wearable" 
            "models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable" 
            "models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable" 
            "models/heroes/terrorblade/wings.vmdl" "wearable" 
            "particle1" 
            { 
            "particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf" 
            "attach" "-1" 
            } 
            "particle3" 
            { 
            "particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf" 
            "attach" "-1" 
            } 
            "particle4" 
            { 
            "particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf" 
            "attach" "-1" 
            } 
            "particle5" 
            { 
            "particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf" 
            "attach" "-1" 
            } 
            "color" 
            { 
            "cp" "15" 
            "1" "255" 
            "2" "255" 
            "3" "0" 
            }
		}

		"391048523"
		{
			"npc_dota_hero_nevermore_alt1" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"54840512"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/promo_trapper_belt/promo_trapper_belt.vmdl" "wearable"
			"models/items/pudge/promo_trapper_arms/promo_trapper_arms.vmdl" "wearable"
			"models/items/pudge/promo_trapper_head/promo_trapper_head.vmdl" "wearable"
			"models/items/pudge/promo_trapper_offhand/promo_trapper_offhand.vmdl" "wearable"
			"models/items/pudge/promo_trapper_shoulder/promo_trapper_shoulder.vmdl" "wearable"
			"models/items/pudge/promo_trapper_weapon/promo_trapper_weapon.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}

		"368968058"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/promo_trapper_belt/promo_trapper_belt.vmdl" "wearable"
			"models/items/pudge/promo_trapper_arms/promo_trapper_arms.vmdl" "wearable"
			"models/items/pudge/promo_trapper_head/promo_trapper_head.vmdl" "wearable"
			"models/items/pudge/promo_trapper_offhand/promo_trapper_offhand.vmdl" "wearable"
			"models/items/pudge/promo_trapper_shoulder/promo_trapper_shoulder.vmdl" "wearable"
			"models/items/pudge/promo_trapper_weapon/promo_trapper_weapon.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}	

		"870553155"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/promo_trapper_belt/promo_trapper_belt.vmdl" "wearable"
			"models/items/pudge/promo_trapper_arms/promo_trapper_arms.vmdl" "wearable"
			"models/items/pudge/promo_trapper_head/promo_trapper_head.vmdl" "wearable"
			"models/items/pudge/promo_trapper_offhand/promo_trapper_offhand.vmdl" "wearable"
			"models/items/pudge/promo_trapper_shoulder/promo_trapper_shoulder.vmdl" "wearable"
			"models/items/pudge/promo_trapper_weapon/promo_trapper_weapon.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}

		"170281422"
		{
			"npc_dota_hero_alchemist" "hero"
			"models/heroes/alchemist/alchemist.vmdl" "model"
			"models/heroes/alchemist/alchemist_ogre_head.vmdl" "wearable"
			"models/heroes/alchemist/alchemist_goblin_head.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_armor/waaagh_alchemist_armor.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_arms/waaagh_alchemist_arms.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_back/waaagh_alchemist_back.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_neck/waaagh_alchemist_neck.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_off_hand/waaagh_alchemist_off_hand.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_shoulder/waaagh_alchemist_shoulder.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_weapon/waaagh_alchemist_weapon.vmdl" "wearable"
			"models/items/alchemist/midasknuckles/midasknuckles.vmdl" "wearable"
		}

		"99888925"
		{
			"npc_dota_hero_terrorblade_alt1" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"126162950"
		{
			"npc_dota_hero_nevermore" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"291593844"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl" "wearable"
			"models/items/antimage/god_eater_arms/god_eater_arms.vmdl" "wearable"
			"models/items/antimage/god_eater_belt/god_eater_belt.vmdl" "wearable"
			"models/items/antimage/god_eater_head/god_eater_head.vmdl" "wearable"
			"models/items/antimage/god_eater_shoulder/god_eater_shoulder.vmdl" "wearable"

			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl_mg" "1"
		}

		"41110316"
		{
			"npc_dota_hero_dazzle" "hero"
			"models/heroes/dazzle/dazzle.vmdl" "model"
			"models/items/dazzle/darkclaw_acolyte_arms/darkclaw_acolyte_arms.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_back/darkclaw_acolyte_back.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_legs/darkclaw_acolyte_legs.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/darkclaw_acolyte_misc.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/mesh/dazzle_darkclaw_acolyte_claw.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/darkclaw_acolyte_weapon.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/mesh/darkclaw_acolyte_claw_fx.vmdl" "wearable"
			"models/items/dazzle/dazzle_ti6_immortal/mesh/dazzle_ti6_immortal.vmdl" "wearable"
			"models/items/dazzle/dazzle_ti6_immortal/mesh/dazzle_ti6_immortal.vmdl_mg" "gold"
		}

		"75997034"
		{
			"npc_dota_hero_legion_commander_alt1" "hero"
			"models/heroes/legion_commander/legion_commander.vmdl" "model"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_shoulder.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_head.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head/stonehall_head.vmdl" "wearable"
			"models/items/legion_commander/legacy_of_the_fallen_legion/legacy_of_the_fallen_legion.vmdl" "wearable"
			"models/items/legion_commander/stonehall_arms/stonehall_arms.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_legs.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl_mg" "1"
			"particle1"
			{
				"particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
			"dualwield" "translate"
		}

		"99707924"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/promo_trapper_belt/promo_trapper_belt.vmdl" "wearable"
			"models/items/pudge/promo_trapper_arms/promo_trapper_arms.vmdl" "wearable"
			"models/items/pudge/promo_trapper_head/promo_trapper_head.vmdl" "wearable"
			"models/items/pudge/promo_trapper_offhand/promo_trapper_offhand.vmdl" "wearable"
			"models/items/pudge/promo_trapper_shoulder/promo_trapper_shoulder.vmdl" "wearable"
			"models/items/pudge/promo_trapper_weapon/promo_trapper_weapon.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}

		"55428680"
		{
			"npc_dota_hero_faceless_void" "hero"
			"models/items/courier/faceless_rex/faceless_rex.vmdl" "model"
			"1.5" "scale"
		}

		"315470704"
		{
			"npc_dota_hero_nevermore" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"114178619"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"436851017" 
		{
			"npc_dota_hero_life_stealer" "hero"
			"models/heroes/life_stealer/life_stealer.vmdl" "model"
			"models/items/lifestealer/ravenous_arms/ravenous_arms.vmdl" "wearable"
			"models/items/lifestealer/ravenous_back/ravenous_back.vmdl" "wearable"
			"models/items/lifestealer/ravenous_belt/ravenous_belt.vmdl" "wearable"
			"models/items/lifestealer/ravenous_head/ravenous_head.vmdl" "wearable"
		}

		"164268113"
		{
			"npc_dota_hero_nevermore" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"289413364"
		{
			"npc_dota_hero_meepo" "hero"
			"models/heroes/meepo/meepo.vmdl" "model"
			"models/items/meepo/the_family_values_arms/the_family_values_arms.vmdl" "wearable"
			"models/items/meepo/the_family_values_back/the_family_values_back.vmdl" "wearable"
			"models/items/meepo/the_family_values_head/the_family_values_head.vmdl" "wearable"
			"models/items/meepo/the_family_values_shoulders/the_family_values_shoulders.vmdl" "wearable"
			"models/items/meepo/the_family_values_tail/the_family_values_tail.vmdl" "wearable"
			"models/items/meepo/the_family_values_weapon/the_family_values_weapon.vmdl" "wearable"
		}

		"427341314"
		{
			"npc_dota_hero_nevermore" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"421647980" 
		{
			"npc_dota_hero_life_stealer" "hero"
			"models/heroes/life_stealer/life_stealer.vmdl" "model"
			"models/items/lifestealer/bloody_ripper_arms/bloody_ripper_arms.vmdl" "wearable"
			"models/items/lifestealer/bloody_ripper_back/bloody_ripper_back.vmdl" "wearable"
			"models/items/lifestealer/bloody_ripper_belt/bloody_ripper_belt.vmdl" "wearable"
			"models/items/lifestealer/bloody_ripper_head/bloody_ripper_head.vmdl" "wearable"
		}

		"199846592"
		{
			"npc_dota_hero_warlock" "hero"
			"models/items/warlock/golem/hellsworn_golem/hellsworn_golem.vmdl" "model"
		}

		"80161021"
		{
			"npc_dota_hero_crystal_maiden" "hero"
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable"
			"models/heroes/crystal_maiden/head_item.vmdl" "wearable"
			"models/heroes/crystal_maiden/crystal_maiden_shoulders.vmdl" "wearable"
			"models/heroes/crystal_maiden/crystal_maiden_staff.vmdl" "wearable"
		}
		"115842333"
		{
			"npc_dota_hero_wisp" "hero"
			"models/items/io/io_ti7/io_ti7.vmdl" "model"
			"particle1" 
			{
				"particle" "particles/econ/items/wisp/wisp_ambient_ti7.vpcf"
				"attach" "PATTACH_OVERHEAD_FOLLOW"
			}
			"particle2" 
			{
				"particle" "particles/econ/items/wisp/wisp_ambient_ti7_trace_glow.vpcf"
				"attach" "PATTACH_POINT_FOLLOW"
			}
			"ACT_DOTA_IDLE" "animation"
		}
		"234197909"
		{
			"npc_dota_hero_spectre" "hero"
			"models/heroes/spectre/spectre.vmdl" "model"
			"models/items/spectre/entropy_belt/entropy_belt.vmdl" "wearable"
			"models/items/spectre/entropy_head/entropy_head.vmdl" "wearable"
			"models/items/spectre/entropy_misc/entropy_misc.vmdl" "wearable"
			"models/items/spectre/entropy_shoulders/entropy_shoulders.vmdl" "wearable"
			"models/items/spectre/entropy_weapon/entropy_weapon.vmdl" "wearable"
		}
		"208624781"
		{
			
			"npc_dota_hero_lycan" "hero"
			"models/items/lycan/ultimate/alpha_trueform9/alpha_trueform9.vmdl" "model"
			"models/items/enchantress/enchantress_crown.vmdl" "wearable"
		}
		"213808733"
		{
			"npc_dota_hero_lycan" "hero"
			"models/items/lycan/ultimate/thegreatcalamityti4/thegreatcalamityti4.vmdl" "model"
		}
		"399710802"
		{
			"npc_dota_hero_tinker" "hero"
			"models/heroes/tinker/tinker.vmdl" "model"
			"models/heroes/tinker/tinker_body_head.vmdl" "wearable"
			"models/items/tinker/roller_mawster/roller_mawster.vmdl" "wearable"
			"models/heroes/tinker/tinker_left_arm.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_weapon_alt/artillery_of_the_fortified_fabricator_weapon_alt.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_shoulder_alt/artillery_of_the_fortified_fabricator_shoulder_alt.vmdl" "wearable"
			"models/items/tinker/boots_of_travel.vmdl" "wearable"
		}
		"61750908"
		{
			"npc_dota_hero_tinker" "hero"
			"models/heroes/tinker/tinker.vmdl" "model"
			"models/heroes/tinker/tinker_body_head.vmdl" "wearable"
			"models/items/tinker/roller_mawster/roller_mawster.vmdl" "wearable"
			"models/heroes/tinker/tinker_left_arm.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_weapon_alt/artillery_of_the_fortified_fabricator_weapon_alt.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_shoulder_alt/artillery_of_the_fortified_fabricator_shoulder_alt.vmdl" "wearable"
			"models/items/tinker/boots_of_travel.vmdl" "wearable"
		}
		"229973029"
		{
			"npc_dota_hero_dazzle" "hero"
			"models/heroes/dazzle/dazzle.vmdl" "model"
			"models/items/dazzle/darkclaw_acolyte_arms/darkclaw_acolyte_arms.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_back/darkclaw_acolyte_back.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_legs/darkclaw_acolyte_legs.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/darkclaw_acolyte_misc.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/mesh/dazzle_darkclaw_acolyte_claw.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/darkclaw_acolyte_weapon.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/mesh/darkclaw_acolyte_claw_fx.vmdl" "wearable"
		}
		"177714054"
		{
			"npc_dota_hero_kunkka" "hero"
			"models/heroes/kunkka/kunkka.vmdl" "model"
			"models/items/kunkka/inquisitor_tide_back/inquisitor_tide_back.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_belt/inquisitor_tide_belt.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_glove/inquisitor_tide_glove.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_head/inquisitor_tide_head.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_legs/inquisitor_tide_legs.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_misc/inquisitor_tide_misc.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_shoulder/inquisitor_tide_shoulder.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_weapon/inquisitor_tide_weapon.vmdl" "wearable"
		}
		"282108122" 
		{
			"npc_dota_hero_lone_druid" "hero"
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
		}
		"120173858"
		{
			"npc_dota_hero_queenofpain" "hero"
			"models/heroes/queenofpain/queenofpain.vmdl" "model"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_back/dotapit_s3_abyssal_temptress_back.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_head/dotapit_s3_abyssal_temptress_head.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_shoulder/dotapit_s3_abyssal_temptress_shoulder.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_weapon/dotapit_s3_abyssal_temptress_weapon.vmdl" "wearable"
		}
		"345384755"
		{
			"npc_dota_hero_meepo" "hero"
			"models/heroes/meepo/meepo.vmdl" "model"
			"models/heroes/meepo/bracers.vmdl" "wearable"
			"models/items/meepo/profitable_adventure_head/profitable_adventure_head.vmdl" "wearable"
			"models/items/meepo/sir_meepalot_weapon/sir_meepalot_weapon.vmdl" "wearable"
			"models/items/meepo/colossal_crystal_chorus/colossal_crystal_chorus.vmdl" "wearable"
		}
		"849777283" 
		{
			"npc_dota_hero_slark" "hero"
			"models/heroes/slark/slark.vmdl" "model"
			"models/items/slark/slark_head_immortal/slark_head_immortal.vmdl" "wearable"
			"models/items/slark/pale_justice/pale_justice.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_shoulder/deep_sea_dragoon_shoulder.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_arms/deep_sea_dragoon_arms.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_back/deep_sea_dragoon_back.vmdl" "wearable"
		}
		"343364427"
		{
			"npc_dota_hero_terrorblade_alt1" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model" 
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
			"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "0"
				"2" "255"
				"3" "0"
			}
		}
		"147822742"
		{
			"npc_dota_hero_terrorblade_alt1" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/terrorblade_ti8_immortal_back/terrorblade_ti8_immortal_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle2" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "0"
				"2" "255"
				"3" "0"
			}
		}
		"115096756"
		{ 
"npc_dota_hero_phoenix_alt1" "hero" 
"models/heroes/phoenix/phoenix_bird.vmdl" "model" 
"models/items/phoenix/blazing_wing_fire_wings/blazing_wing_fire_wings.vmdl" "wearable" 
"models/items/phoenix/solar_forge/mesh/solar_forge_model.vmdl" "wearable" 
"models/items/phoenix/blazing_wing_fire_wings/blazing_wing_fire_wings_fx.vmdl" "wearable" 


"particle1" 
{ 
"particle" "particles/econ/items/phoenix/phoenix_solar_forge/phoenix_solar_forge_ambient.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/units/heroes/hero_phoenix/phoenix_ambient.vpcf" 
"attach" "-1" 
} 

}
        "141860097"
		{
			"npc_dota_hero_meepo" "hero"
			"models/heroes/meepo/meepo.vmdl" "model"
			"models/items/meepo/the_family_values_arms/the_family_values_arms.vmdl" "wearable"
			"models/items/meepo/the_family_values_back/the_family_values_back.vmdl" "wearable"
			"models/items/meepo/meepo_skeletonkey_bandana/meepo_skeletonkey_bandana.vmdl" "wearable"
			"models/items/meepo/the_family_values_shoulders/the_family_values_shoulders.vmdl" "wearable"
			"models/items/meepo/the_family_values_tail/the_family_values_tail.vmdl" "wearable"
			"models/items/meepo/meepo_skeletonkey_sword/meepo_skeletonkey_sword.vmdl" "wearable"
		}
		"114472632"
		{
		    "npc_dota_hero_witch_doctor" "hero"
			"models/heroes/witchdoctor/witchdoctor.vmdl" "model"
			"models/items/witchdoctor/stormcrowmask/stormcrowmask.vmdl" "wearable"
			"models/items/witchdoctor/salted_voodoo_dog_back/salted_voodoo_dog_back.vmdl" "wearable"
			"models/items/witchdoctor/vermilion_juju_of_the_south_weapon/vermilion_juju_of_the_south_weapon.vmdl" "wearable"
			"models/items/witchdoctor/vermilion_juju_of_the_south_shoulder/vermilion_juju_of_the_south_shoulder.vmdl" "wearable"
			"models/items/witchdoctor/vermilion_juju_of_the_south_belt/vermilion_juju_of_the_south_belt.vmdl" "wearable"
		}
		"96034076"//"96034076"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_navi.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
		"200798690"
		{
		    "npc_dota_hero_tinker" "hero"
			"models/heroes/tinker/tinker.vmdl" "model"
			"models/items/tinker/artillery_of_the_fortified_fabricator_head/artillery_of_the_fortified_fabricator_head.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_back_alt/artillery_of_the_fortified_fabricator_back_alt.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_off_hand_alt/artillery_of_the_fortified_fabricator_off_hand_alt.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_shoulder_alt/artillery_of_the_fortified_fabricator_shoulder_alt.vmdl" "wearable"
			"models/items/tinker/artillery_of_the_fortified_fabricator_weapon_alt/artillery_of_the_fortified_fabricator_weapon_alt.vmdl" "wearable"
			"models/heroes/tinker/tinker_body_head.vmdl" "wearable"
		}
		"973898809"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_navi.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
		"80698083"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_navi.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
		"203310901"
		{
			"npc_dota_hero_terrorblade_alt1" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}
		"170117791"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_navi.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
	}
	"petrosyan"
	{
		"english"
		{
			"models/heroes/brewmaster/brewmaster.vmdl" "model"
			"models/items/brewmaster/reddragon_arms/reddragon_arms.vmdl" "wearable"
			"models/items/brewmaster/reddragon_back/reddragon_back.vmdl" "wearable"
			"models/items/brewmaster/reddragon_offhand/reddragon_offhand.vmdl" "wearable"
			"models/items/brewmaster/reddragon_shoulder/reddragon_shoulder.vmdl" "wearable"
			"models/items/brewmaster/reddragon_weapon/reddragon_weapon.vmdl" "wearable"
		}
		"russian"
		{
			"models/heroes/brewmaster/brewmaster.vmdl" "model"
			"models/items/brewmaster/reddragon_arms/reddragon_arms.vmdl" "wearable"
			"models/items/brewmaster/reddragon_back/reddragon_back.vmdl" "wearable"
			"models/items/brewmaster/reddragon_offhand/reddragon_offhand.vmdl" "wearable"
			"models/items/brewmaster/reddragon_shoulder/reddragon_shoulder.vmdl" "wearable"
			"models/items/brewmaster/reddragon_weapon/reddragon_weapon.vmdl" "wearable"
		}
		"275002088"
    {
    "npc_dota_hero_legion_commander_alt1" "hero"
    "models/heroes/legion_commander/legion_commander.vmdl" "model"
    "models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_shoulder.vmdl" "wearable"
    "models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_head.vmdl" "wearable"
    "models/items/legion_commander/legacy_of_the_fallen_legion/legacy_of_the_fallen_legion.vmdl" "wearable"
    "models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_legs.vmdl" "wearable"
    "models/items/legion_commander/demon_sword.vmdl" "wearable"
    "models/items/legion_commander/demon_sword.vmdl_mg" "1"
    "particle1"
    {
        "particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient_alt_feathers_r_glow.vpcf"
        "attach" "-1"
    }
    "particle2"
    {
        "particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient_alt_feathers_l_glow.vpcf"
        "attach" "-1"
    }
    "particle3"
    {
        "particle" "particles/econ/items/legion/legion_fallen/legion_fallen_press_owner_l_alt_3.vpcf"
        "attach" "-1"
    }
    "particle4"
    {
        "particle" "particles/econ/items/legion/legion_fallen/legion_fallen_press_owner_r_alt_3.vpcf"
        "attach" "-1"
    }
    "1" "material_group"
    "1.0" "scale"
    "dualwield" "translate"
    }
		"11"//295394717
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl" "wearable"
			"models/items/antimage/god_eater_arms/god_eater_arms.vmdl" "wearable"
			"models/items/antimage/god_eater_belt/god_eater_belt.vmdl" "wearable"
			"models/items/antimage/god_eater_head/god_eater_head.vmdl" "wearable"
			"models/items/antimage/god_eater_shoulder/god_eater_shoulder.vmdl" "wearable"

			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl_mg" "1"
		}
		"439495615"
		{
			"npc_dota_hero_meepo" "hero"
			"models/heroes/meepo/meepo.vmdl" "model"
			"models/items/meepo/the_family_values_arms/the_family_values_arms.vmdl" "wearable"
			"models/items/meepo/the_family_values_back/the_family_values_back.vmdl" "wearable"
			"models/items/meepo/the_family_values_head/the_family_values_head.vmdl" "wearable"
			"models/items/meepo/the_family_values_shoulders/the_family_values_shoulders.vmdl" "wearable"
			"models/items/meepo/the_family_values_tail/the_family_values_tail.vmdl" "wearable"
			"models/items/meepo/the_family_values_weapon/the_family_values_weapon.vmdl" "wearable"
		}
		"326455601"
		{
			"npc_dota_hero_legion_commander_alt1" "hero"
			"models/heroes/legion_commander/legion_commander.vmdl" "model"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_shoulder.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_head.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head/stonehall_head.vmdl" "wearable"
			"models/items/legion_commander/legacy_of_the_fallen_legion/legacy_of_the_fallen_legion.vmdl" "wearable"
			"models/items/legion_commander/stonehall_arms/stonehall_arms.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_legs.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl_mg" "1"
			"particle1"
			{
				"particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
			"dualwield" "translate"		
		}
		"377139128"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl" "wearable"
			"models/items/antimage/god_eater_arms/god_eater_arms.vmdl" "wearable"
			"models/items/antimage/god_eater_belt/god_eater_belt.vmdl" "wearable"
			"models/items/antimage/god_eater_head/god_eater_head.vmdl" "wearable"
			"models/items/antimage/god_eater_shoulder/god_eater_shoulder.vmdl" "wearable"

			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl_mg" "1"
		}
		"889464008"
		{
			"npc_dota_hero_meepo" "hero"
			"models/heroes/meepo/meepo.vmdl" "model"
			"models/items/meepo/the_family_values_arms/the_family_values_arms.vmdl" "wearable"
			"models/items/meepo/the_family_values_back/the_family_values_back.vmdl" "wearable"
			"models/items/meepo/the_family_values_head/the_family_values_head.vmdl" "wearable"
			"models/items/meepo/the_family_values_shoulders/the_family_values_shoulders.vmdl" "wearable"
			"models/items/meepo/the_family_values_tail/the_family_values_tail.vmdl" "wearable"
			"models/items/meepo/the_family_values_weapon/the_family_values_weapon.vmdl" "wearable"
			
			"particle1"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_liquid.vpcf"
				"attach" "-1"
			}
		}
		"190074651"
		{
			"npc_dota_hero_legion_commander_alt1" "hero"
			"models/heroes/legion_commander/legion_commander.vmdl" "model"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_shoulder.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_head.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head/stonehall_head.vmdl" "wearable"
			"models/items/legion_commander/legacy_of_the_fallen_legion/legacy_of_the_fallen_legion.vmdl" "wearable"
			"models/items/legion_commander/stonehall_arms/stonehall_arms.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_legs.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl_mg" "1"
			"particle1"
			{
				"particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
			"dualwield" "translate"
		}
		"132163810"
		{
		    "npc_dota_hero_terrorblade_alt1" "hero" 
            "models/heroes/terrorblade/terrorblade.vmdl" "model" 
            "models/heroes/terrorblade/horns_arcana.vmdl" "wearable" 
            "models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable" 
            "models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable" 
            "models/heroes/terrorblade/wings.vmdl" "wearable" 
            "particle1" 
            { 
            "particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf" 
            "attach" "-1" 
            } 
            "particle3" 
            { 
            "particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf" 
            "attach" "-1" 
            } 
            "particle4" 
            { 
            "particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf" 
            "attach" "-1" 
            } 
            "particle5" 
            { 
            "particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf" 
            "attach" "-1" 
            } 
            "color" 
            { 
            "cp" "15" 
            "1" "255" 
            "2" "255" 
            "3" "255" 
            }
		}
		"133531922"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl" "wearable"
			"models/items/antimage/god_eater_arms/god_eater_arms.vmdl" "wearable"
			"models/items/antimage/god_eater_belt/god_eater_belt.vmdl" "wearable"
			"models/items/antimage/god_eater_head/god_eater_head.vmdl" "wearable"
			"models/items/antimage/god_eater_shoulder/god_eater_shoulder.vmdl" "wearable"

			"models/items/antimage/ti7_antimage_immortal/ti7_immortal_armor.vmdl_mg" "1"
		}
		"383464208"
		{
		    "npc_dota_hero_terrorblade_alt1" "hero" 
            "models/heroes/terrorblade/terrorblade.vmdl" "model" 
            "models/heroes/terrorblade/horns_arcana.vmdl" "wearable" 
            "models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable" 
            "models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable" 
            "models/heroes/terrorblade/wings.vmdl" "wearable" 
            "particle1" 
            { 
            "particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf" 
            "attach" "-1" 
            } 
            "particle3" 
            { 
            "particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf" 
            "attach" "-1" 
            } 
            "particle4" 
            { 
            "particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf" 
            "attach" "-1" 
            } 
            "particle5" 
            { 
            "particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf" 
            "attach" "-1" 
            } 
            "color" 
            { 
            "cp" "15" 
            "1" "255" 
            "2" "0" 
            "3" "0" 
            }
		}
		"123270901"
		{
			"npc_dota_hero_slark" "hero"
			"models/heroes/slark/slark.vmdl" "model"
			"models/items/slark/slark_head_immortal/slark_head_immortal.vmdl" "wearable"
			"models/items/slark/pale_justice/pale_justice.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_shoulder/deep_sea_dragoon_shoulder.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_arms/deep_sea_dragoon_arms.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_back/deep_sea_dragoon_back.vmdl" "wearable"
		}
				"115096756"
		{ 
"npc_dota_hero_phoenix_alt1" "hero" 
"models/heroes/phoenix/phoenix_bird.vmdl" "model" 
"models/items/phoenix/blazing_wing_fire_wings/blazing_wing_fire_wings.vmdl" "wearable" 
"models/items/phoenix/solar_forge/mesh/solar_forge_model.vmdl" "wearable" 
"models/items/phoenix/blazing_wing_fire_wings/blazing_wing_fire_wings_fx.vmdl" "wearable" 


"particle1" 
{ 
"particle" "particles/econ/items/phoenix/phoenix_solar_forge/phoenix_solar_forge_ambient.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/units/heroes/hero_phoenix/phoenix_ambient.vpcf" 
"attach" "-1" 
} 

}
		
				"148967307"
		{
		"npc_dota_hero_crystal_maiden" "hero" 
"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model" 
"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_head/warden_icewrack_head.vmdl" "wearable" 
"models/items/crystal_maiden/immortal_shoulders/cm_immortal_shoulders.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_staff/warden_icewrack_staff.vmdl" "wearable" 
"models/items/crystal_maiden/crystalline_empress_arms/crystalline_empress_arms.vmdl" "wearable" 

"particle1" 
{ 
"particle" "particles/maiden_freezing_field_casterribbons_arcana1_custom.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient.vpcf" 
"attach" "-1" 
} 


"particle5" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_ball_sparks.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_halo.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient.vpcf" 
"attach" "-1" 
} 

"particle7" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
} 
"particle8" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_ground_ambient.vpcf" 
"attach" "-1" 
} 
"particle9" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle10" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle11" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient.vpcf" 
"attach" "-1" 
} 
"particle12" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle13" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle14" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_d.vpcf" 
"attach" "-1" 
} 
"particle15" 
{ 
"particle" "particles/econ/items/pangolier/pangolier_ti8_immortal/pangolier_ti8_immortal_ambient_hearts.vpcf" 
"attach" "-1" 
} 
"particle16" 
{ 
"particle" "particles/units/heroes/hero_tusk/tusk_frozen_sigil.vpcf" 
"attach" "-1" 
} 

"particle18" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
}
		}


		"343364427"
		{
			"npc_dota_hero_slark" "hero"
			"models/heroes/slark/slark.vmdl" "model"
			"models/items/slark/slark_head_immortal/slark_head_immortal.vmdl" "wearable"
			"models/items/slark/pale_justice/pale_justice.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_shoulder/deep_sea_dragoon_shoulder.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_arms/deep_sea_dragoon_arms.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_back/deep_sea_dragoon_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_blade_ambient_c.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient.vpcf"
			"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_e.vpcf"
				"attach" "-1"
			}
			"particle6" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_gilded_edge_blade_ambient.vpcf"
				"attach" "-1"
			}
			"particle7" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_gilded_edge_blade_ambient_b.vpcf"
				"attach" "-1"
			}
			"particle8" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_e.vpcf"
				"attach" "-1"
			}
			"particle9" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_b.vpcf"
				"attach" "-1"
			}
			"particle10" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_c.vpcf"
				"attach" "-1"
			}
			"particle11" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_d.vpcf"
				"attach" "-1"
			}
			"particle12" 
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient_edge_flame.vpcf"
				"attach" "-1"
			}
			"particle13" 
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient_edge_glow.vpcf"
				"attach" "-1"
			}
			"particle14" 
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient_edge.vpcf"
				"attach" "-1"
			}


		}
		

		"147822742"
		{
			"npc_dota_hero_slark" "hero"
			"models/heroes/slark/slark.vmdl" "model"
			"models/items/slark/slark_head_immortal/slark_head_immortal.vmdl" "wearable"
			"models/items/slark/pale_justice/pale_justice.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_shoulder/deep_sea_dragoon_shoulder.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_arms/deep_sea_dragoon_arms.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_back/deep_sea_dragoon_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_blade_ambient_c.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient.vpcf"
			"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_e.vpcf"
				"attach" "-1"
			}
			"particle6" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_gilded_edge_blade_ambient.vpcf"
				"attach" "-1"
			}
			"particle7" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_gilded_edge_blade_ambient_b.vpcf"
				"attach" "-1"
			}
			"particle8" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_e.vpcf"
				"attach" "-1"
			}
			"particle9" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_b.vpcf"
				"attach" "-1"
			}
			"particle10" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_c.vpcf"
				"attach" "-1"
			}
			"particle11" 
			{
				"particle" "particles/econ/items/slark/slark_pale_edge/slark_pale_edge_gem_ambient_d.vpcf"
				"attach" "-1"
			}
			"particle12" 
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient_edge_flame.vpcf"
				"attach" "-1"
			}
			"particle13" 
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient_edge_glow.vpcf"
				"attach" "-1"
			}
			"particle14" 
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient_edge.vpcf"
				"attach" "-1"
			}
			"particle15"
			{
				"particle" "particles/econ/items/slark/slark_head_immortal/slark_head_immortal_ambient_eye.vpcf"
				"attach" "-1"
			}


		}



		"316050477"
		{
			"npc_dota_hero_terrorblade_alt1" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"54840512"
		{
			"npc_dota_hero_dazzle" "hero"
			"models/heroes/dazzle/dazzle.vmdl" "model"
			"models/items/dazzle/darkclaw_acolyte_arms/darkclaw_acolyte_arms.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_back/darkclaw_acolyte_back.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_legs/darkclaw_acolyte_legs.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/darkclaw_acolyte_misc.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/mesh/dazzle_darkclaw_acolyte_claw.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/darkclaw_acolyte_weapon.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/mesh/darkclaw_acolyte_claw_fx.vmdl" "wearable"
			"models/items/dazzle/dazzle_ti6_immortal/mesh/dazzle_ti6_immortal.vmdl" "wearable"
			"models/items/dazzle/dazzle_ti6_immortal/mesh/dazzle_ti6_immortal.vmdl_mg" "gold"
		}

		"391048523"
		{
			"npc_dota_hero_nevermore_alt1" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"219047091"
		{
			"npc_dota_hero_nevermore_alt1" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"291593844"
		{
			"npc_dota_hero_ember_spirit" "hero"
			"models/heroes/ember_spirit/ember_spirit.vmdl" "model"
			"models/items/ember_spirit/vanishing_flame_arms/vanishing_flame_arms.vmdl" "wearable"
			"models/items/ember_spirit/vanishing_flame_belt/vanishing_flame_belt.vmdl" "wearable"
			"models/items/ember_spirit/vanishing_flame_head/vanishing_flame_head.vmdl" "wearable"
			"models/items/ember_spirit/vanishing_flame_shoulder/vanishing_flame_shoulder.vmdl" "wearable"
			"models/items/ember_spirit/rapier_burning_god_offhand/rapier_burning_god_offhand.vmdl" "wearable"
			"models/items/ember_spirit/rapier_burning_god_weapon/rapier_burning_god_weapon.vmdl" "wearable"
		}

		"870553155"
		{
			"npc_dota_hero_terrorblade_alt1" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"170281422"
		{
			"npc_dota_hero_queenofpain" "hero"
			"models/heroes/queenofpain/queenofpain.vmdl" "model"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_back/dotapit_s3_abyssal_temptress_back.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_head/dotapit_s3_abyssal_temptress_head.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_shoulder/dotapit_s3_abyssal_temptress_shoulder.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_weapon/dotapit_s3_abyssal_temptress_weapon.vmdl" "wearable"
			"models/items/doom/abysssword/abysssword.vmdl" "wearable"
		}

		"99888925" 
		{
			"npc_dota_hero_life_stealer" "hero"
			"models/heroes/life_stealer/life_stealer.vmdl" "model"
			"models/items/lifestealer/ravenous_arms/ravenous_arms.vmdl" "wearable"
			"models/items/lifestealer/ravenous_back/ravenous_back.vmdl" "wearable"
			"models/items/lifestealer/ravenous_belt/ravenous_belt.vmdl" "wearable"
			"models/items/lifestealer/ravenous_head/ravenous_head.vmdl" "wearable"
		}

		"99707924"
		{
			"npc_dota_hero_terrorblade_alt1" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/terrorblade_ti8_immortal_back/terrorblade_ti8_immortal_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle2" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "225"
				"2" "44"
				"3" "44"
			}
		}

		"849777283" 
		{
			"npc_dota_hero_juggernaut" "hero"
			"models/heroes/juggernaut/juggernaut.vmdl" "model"
			"models/items/juggernaut/armor_for_the_favorite_arms/armor_for_the_favorite_arms.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_back/armor_for_the_favorite_back.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_head/armor_for_the_favorite_head.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_legs/armor_for_the_favorite_legs.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_weapon/armor_for_the_favorite_weapon.vmdl" "wearable"
		}

		"126162950"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"55428680"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"315470704"
		{
			"npc_dota_hero_sven" "hero"
			"models/heroes/sven/sven.vmdl" "model"
			"models/items/sven/sven_ti7_immortal_sword/sven_ti7_immortal_sword.vmdl" "wearable"
			"models/items/sven/sven_ceremonialgreathelmofthemyrmidon/sven_ceremonialgreathelmofthemyrmidon.vmdl" "wearable"
			"models/items/sven/rhinoceros_shoulder/rhinoceros_shoulder.vmdl" "wearable"
			"models/items/sven/knight_skirt.vmdl" "wearable"
			"models/items/sven/arbiter_arms/arbiter_arms.vmdl" "wearable"
			//"odachi" "translate"
		}

		"130530419"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"294152893"
		{
			"npc_dota_hero_sven" "hero"
			"models/heroes/sven/sven.vmdl" "model"
			"models/items/sven/sven_ti7_immortal_sword/sven_ti7_immortal_sword.vmdl" "wearable"
			"models/items/sven/sven_ceremonialgreathelmofthemyrmidon/sven_ceremonialgreathelmofthemyrmidon.vmdl" "wearable"
			"models/items/sven/rhinoceros_shoulder/rhinoceros_shoulder.vmdl" "wearable"
			"models/items/sven/knight_skirt.vmdl" "wearable"
			"models/items/sven/arbiter_arms/arbiter_arms.vmdl" "wearable"
			//"odachi" "translate"
		}

		"114178619"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"436851017" 
		{
			"npc_dota_hero_juggernaut" "hero"
			"models/heroes/juggernaut/juggernaut.vmdl" "model"
			"models/items/juggernaut/armor_for_the_favorite_arms/armor_for_the_favorite_arms.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_back/armor_for_the_favorite_back.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_head/armor_for_the_favorite_head.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_legs/armor_for_the_favorite_legs.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_weapon/armor_for_the_favorite_weapon.vmdl" "wearable"
		}

		"164268113"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"122891387"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"289413364"
		{
			"npc_dota_hero_chaos_knight" "hero"
			"models/heroes/chaos_knight/chaos_knight.vmdl" "model"
			"models/items/chaos_knight/lighthunter_mount/lighthunter_mount.vmdl" "wearable"
			"models/items/chaos_knight/face_of_entropy/face_of_entropy.vmdl" "wearable"
			"models/items/chaos_knight/burning_nightmare_chaos_knight_weapon/burning_nightmare_chaos_knight_weapon.vmdl" "wearable"
			"models/items/chaos_knight/oni_knight_the_dark_conqueror_shoulder/oni_knight_the_dark_conqueror_shoulder.vmdl" "wearable"
			"models/items/chaos_knight/chaos_knight_ti7_shield/chaos_knight_ti7_shield.vmdl" "wearable"
		}

		"427341314"
		{
			"npc_dota_hero_doom_bringer" "hero"
			"models/heroes/doom/doom.vmdl" "model"
			"models/items/doom/baphomet_arms/baphomet_arms.vmdl" "wearable"
			"models/items/doom/baphomet_belt/baphomet_belt.vmdl" "wearable"
			"models/items/doom/baphomet_cloak/baphomet_cloak.vmdl" "wearable"
			"models/items/doom/baphomet_head/baphomet_head.vmdl" "wearable"
			"models/items/doom/baphomet_tail/baphomet_tail.vmdl" "wearable"
			"models/items/doom/baphomet_weapon/baphomet_weapon.vmdl" "wearable"
			"models/items/doom/baphomet_wings/baphomet_wings.vmdl" "wearable"
		}

		"421647980"
		{
			"npc_dota_hero_doom_bringer" "hero"
			"models/heroes/doom/doom.vmdl" "model"
			"models/items/doom/baphomet_arms/baphomet_arms.vmdl" "wearable"
			"models/items/doom/baphomet_belt/baphomet_belt.vmdl" "wearable"
			"models/items/doom/baphomet_cloak/baphomet_cloak.vmdl" "wearable"
			"models/items/doom/baphomet_head/baphomet_head.vmdl" "wearable"
			"models/items/doom/baphomet_tail/baphomet_tail.vmdl" "wearable"
			"models/items/doom/baphomet_weapon/baphomet_weapon.vmdl" "wearable"
			"models/items/doom/baphomet_wings/baphomet_wings.vmdl" "wearable"
		}

		"199846592"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
			// "npc_dota_hero_sand_king" "hero"
			// "models/heroes/sand_king/sand_king.vmdl" "model"
			// "models/items/sand_king/elusive_destroyer_arms/elusive_destroyer_arms.vmdl" "wearable"
			// "models/items/sand_king/elusive_destroyer_back/elusive_destroyer_back.vmdl" "wearable"
			// "models/items/sand_king/elusive_destroyer_head/elusive_destroyer_head.vmdl" "wearable"
			// "models/items/sand_king/elusive_destroyer_legs/elusive_destroyer_legs.vmdl" "wearable"
			// "models/items/sand_king/elusive_destroyer_shoulder/elusive_destroyer_shoulder.vmdl" "wearable"			
		}

		"41110316" 
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"105773141"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_armor/tarrasque_scale_armor.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_arms/tarrasque_scale_arms.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_belt/tarrasque_scale_belt.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_head/tarrasque_scale_head.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_shoulder/tarrasque_scale_shoulder.vmdl" "wearable"
			"petri_petrosyan_flat_joke"
			{
				"anim" "ACT_DOTA_ATTACK_EVENT_BASH"
				"translate" "basher"
				"sound" "Hero_Antimage.ManaBreak"
			}
		}

		"80161021"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_armor/tarrasque_scale_armor.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_arms/tarrasque_scale_arms.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_belt/tarrasque_scale_belt.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_head/tarrasque_scale_head.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_shoulder/tarrasque_scale_shoulder.vmdl" "wearable"
			"petri_petrosyan_flat_joke"
			{
				"anim" "ACT_DOTA_ATTACK_EVENT_BASH"
				"translate" "basher"
				"sound" "Hero_Antimage.ManaBreak"
			}
		}
		"110299827"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_armor/tarrasque_scale_armor.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_arms/tarrasque_scale_arms.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_belt/tarrasque_scale_belt.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_head/tarrasque_scale_head.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_shoulder/tarrasque_scale_shoulder.vmdl" "wearable"
			"petri_petrosyan_flat_joke"
			{
				"anim" "ACT_DOTA_ATTACK_EVENT_BASH"
				"translate" "basher"
				"sound" "Hero_Antimage.ManaBreak"
			}
		}
		"115842333"
		{
			"npc_dota_hero_ursa" "hero"
			"models/heroes/ursa/ursa.vmdl" "model"
			"models/items/ursa/gloves_alpine.vmdl" "wearable"
			"models/items/ursa/hat_alpine.vmdl" "wearable"
			"models/items/ursa/pants_alpine.vmdl" "wearable"
			"models/items/ursa/scarf_alpine.vmdl" "wearable"
		}
		// "41110316" 
		// {
		// 	"npc_dota_hero_terrorblade" "hero"
		// 	"models/items/terrorblade/dotapit_s3_fallen_light_metamorphosis/dotapit_s3_fallen_light_metamorphosis.vmdl" "model"
		// }
		"234197909"
		{
			"npc_dota_hero_spectre" "hero"
			"models/heroes/spectre/spectre.vmdl" "model"
			"models/items/spectre/entropy_belt/entropy_belt.vmdl" "wearable"
			"models/items/spectre/entropy_head/entropy_head.vmdl" "wearable"
			"models/items/spectre/entropy_misc/entropy_misc.vmdl" "wearable"
			"models/items/spectre/entropy_shoulders/entropy_shoulders.vmdl" "wearable"
			"models/items/spectre/entropy_weapon/entropy_weapon.vmdl" "wearable"
		}
		"208624781"
		{
			
			"npc_dota_hero_lycan" "hero"
			"models/items/lycan/ultimate/alpha_trueform9/alpha_trueform9.vmdl" "model"
			"models/items/enchantress/enchantress_crown.vmdl" "wearable"
		}
		"213808733"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/items/terrorblade/dotapit_s3_fallen_light_metamorphosis/dotapit_s3_fallen_light_metamorphosis.vmdl" "model"
		}
		"61750908"
		{
			"models/heroes/kunkka/kunkka.vmdl" "model"
			"models/items/kunkka/inquisitor_tide_back/inquisitor_tide_back.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_belt/inquisitor_tide_belt.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_glove/inquisitor_tide_glove.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_head/inquisitor_tide_head.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_legs/inquisitor_tide_legs.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_misc/inquisitor_tide_misc.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_shoulder/inquisitor_tide_shoulder.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_weapon/inquisitor_tide_weapon.vmdl" "wearable"
		}
		"229973029"
		{
			"npc_dota_hero_dazzle" "hero"
			"models/heroes/dazzle/dazzle.vmdl" "model"
			"models/items/dazzle/darkclaw_acolyte_arms/darkclaw_acolyte_arms.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_back/darkclaw_acolyte_back.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_legs/darkclaw_acolyte_legs.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/darkclaw_acolyte_misc.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/mesh/dazzle_darkclaw_acolyte_claw.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/darkclaw_acolyte_weapon.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/mesh/darkclaw_acolyte_claw_fx.vmdl" "wearable"
		}
		"177714054"
		{
			"npc_dota_hero_kunkka" "hero"
			"models/heroes/kunkka/kunkka.vmdl" "model"
			"models/items/kunkka/inquisitor_tide_back/inquisitor_tide_back.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_belt/inquisitor_tide_belt.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_glove/inquisitor_tide_glove.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_head/inquisitor_tide_head.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_legs/inquisitor_tide_legs.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_misc/inquisitor_tide_misc.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_shoulder/inquisitor_tide_shoulder.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_weapon/inquisitor_tide_weapon.vmdl" "wearable"
		}
		"122827578"
		{
			"npc_dota_hero_lone_druid" "hero"
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
			// "models/items/dazzle/darkclaw_acolyte_arms/darkclaw_acolyte_arms.vmdl" "wearable"
			// "models/items/dazzle/darkclaw_acolyte_back/darkclaw_acolyte_back.vmdl" "wearable"
			// "models/items/dazzle/darkclaw_acolyte_legs/darkclaw_acolyte_legs.vmdl" "wearable"
			// "models/items/dazzle/darkclaw_acolyte_misc/darkclaw_acolyte_misc.vmdl" "wearable"
			// "models/items/dazzle/darkclaw_acolyte_misc/mesh/dazzle_darkclaw_acolyte_claw.vmdl" "wearable"
			// "models/items/dazzle/darkclaw_acolyte_weapon/darkclaw_acolyte_weapon.vmdl" "wearable"
			// "models/items/dazzle/darkclaw_acolyte_weapon/mesh/darkclaw_acolyte_claw_fx.vmdl" "wearable"
		}
		"282108122" 
		{
			"npc_dota_hero_lone_druid" "hero"
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
		}
		"345384755"
		{
			"npc_dota_hero_dazzle" "hero"
			"models/heroes/dazzle/dazzle.vmdl" "model"
			"models/items/dazzle/darkclaw_acolyte_arms/darkclaw_acolyte_arms.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_back/darkclaw_acolyte_back.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_legs/darkclaw_acolyte_legs.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/darkclaw_acolyte_misc.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/mesh/dazzle_darkclaw_acolyte_claw.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/darkclaw_acolyte_weapon.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/mesh/darkclaw_acolyte_claw_fx.vmdl" "wearable"
		}
	    "147518249"
{
"npc_dota_hero_crystal_maiden" "hero" 
"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model" 
"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_head/warden_icewrack_head.vmdl" "wearable" 
"models/items/crystal_maiden/immortal_shoulders/cm_immortal_shoulders.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_staff/warden_icewrack_staff.vmdl" "wearable" 
"models/items/crystal_maiden/crystalline_empress_arms/crystalline_empress_arms.vmdl" "wearable" 

"particle1" 
{ 
"particle" "particles/maiden_freezing_field_casterribbons_arcana1_custom.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient.vpcf" 
"attach" "-1" 
} 


"particle5" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_ball_sparks.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_halo.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient.vpcf" 
"attach" "-1" 
} 

"particle7" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
} 
"particle8" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_ground_ambient.vpcf" 
"attach" "-1" 
} 
"particle9" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle10" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle11" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient.vpcf" 
"attach" "-1" 
} 
"particle12" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle13" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle14" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_d.vpcf" 
"attach" "-1" 
} 
"particle15" 
{ 
"particle" "particles/econ/items/pangolier/pangolier_ti8_immortal/pangolier_ti8_immortal_ambient_hearts.vpcf" 
"attach" "-1" 
} 
"particle16" 
{ 
"particle" "particles/units/heroes/hero_tusk/tusk_frozen_sigil.vpcf" 
"attach" "-1" 
} 

"particle18" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
}
}
        "216840474"
		{
		    "npc_dota_hero_phantom_assasin" "hero"
			"models/heroes/phantom_assassin/phantom_assassin.vmdl" "model"
			"models/items/phantom_assassin/ti9_cache_pa_gothic_hunter_shoulder/ti9_cache_pa_gothic_hunter_shoulder.vmdl" "wearable"
			"models/items/phantom_assassin/ti9_cache_pa_gothic_hunter_back/ti9_cache_pa_gothic_hunter_back.vmdl" "wearable"
			"models/items/phantom_assassin/ti9_cache_pa_gothic_hunter_head/ti9_cache_pa_gothic_hunter_head.vmdl" "wearable"
		    "models/items/phantom_assassin/ti9_cache_pa_gothic_hunter_weapon/ti9_cache_pa_gothic_hunter_weapon.vmdl" "wearable"
			"models/items/phantom_assassin/dragonterror_belt/dragonterror_belt.vmdl" "wearable"
			"particle1"
			{
			    "particle" "particles/econ/items/phantom_assassin/ti9_cache_pa_gothic_hunter_weapon/ti9_cache_pa_gothic_weapon_ambient.vpcf"
				"attach" "-1"
			}
			
		}
        "213911362" //213911362
		{
			"npc_dota_hero_templar_assassin" "hero"
			"models/heroes/lanaya/lanaya.vmdl" "model"
			"models/items/lanaya/raiment_of_the_violet_archives_head_hood/raiment_of_the_violet_archives_head_hood.vmdl" "wearable"
			"models/items/lanaya/raiment_of_the_violet_archives_armor/raiment_of_the_violet_archives_armor.vmdl" "wearable"
			"models/items/lanaya/raiment_of_the_violet_archives_shoulder/raiment_of_the_violet_archives_shoulder.vmdl" "wearable"
			
		}
		"96034076"//96034076
		{
			"npc_dota_hero_nevermore_alt1" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}
		
		"200798690"
		{
		    "npc_dota_hero_dragon_knight" "hero"
			"models/heroes/dragon_knight/dragon_knight.vmdl" "model"
			"models/items/dragon_knight/fireborn_helmet/fireborn_helmet.vmdl" "wearable"
			"models/items/dragon_knight/fireborn_arms/fireborn_arms.vmdl" "wearable"			
			"models/items/dragon_knight/fireborn_back/fireborn_back.vmdl" "wearable"
			"models/items/dragon_knight/fireborn_shoulders/fireborn_shoulders.vmdl" "wearable"
			"models/items/dragon_knight/fireborn_shield/fireborn_shield.vmdl" "wearable"
			"models/items/dragon_knight/fireborn_sword/fireborn_sword.vmdl" "wearable"
		}
		
		"138158104"
		{
		    		    "npc_dota_hero_axe" "hero"
			"models/items/axe/ti9_jungle_axe/axe_bare.vmdl" "model"
		}
		"169092221"
		{
			"npc_dota_hero_pudge_alt1" "hero"
			"models/items/pudge/arcana/pudge_arcana_base.vmdl" "model"
			"models/items/pudge/arcana/pudge_arcana_back.vmdl" "wearable"
			"models/items/pudge/ftp_dendi_belt/ftp_dendi_belt.vmdl" "wearable"
			"models/items/pudge/the_devarque_fugitive_arms/the_devarque_fugitive_arms.vmdl" "wearable"
			"models/items/pudge/pudge_deep_sea_abomination_head/pudge_deep_sea_abomination_head.vmdl" "wearable"
			"models/items/pudge/insatiable_bonesaw/insatiable_bonesaw.vmdl" "wearable"
			"models/items/pudge/immortal_arm/immortal_arm.vmdl" "wearable"
			"models/items/pudge/pudge_skeleton_hook.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_back_ambient_beam.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/pudge/pudge_arcana/pudge_arcana_ambient_flies.vpcf"
				"attach" "-1"
			}
			"particle4"
			{
			    "particle" "particles/events/ti6_teams/teleport_start_ti6_lvl3_navi.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
		}
		"849777283" 
		{
			"npc_dota_hero_slark" "hero"
			"models/heroes/slark/slark.vmdl" "model"
			"models/items/slark/slark_head_immortal/slark_head_immortal.vmdl" "wearable"
			"models/items/slark/pale_justice/pale_justice.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_shoulder/deep_sea_dragoon_shoulder.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_arms/deep_sea_dragoon_arms.vmdl" "wearable"
			"models/items/slark/deep_sea_dragoon_back/deep_sea_dragoon_back.vmdl" "wearable"
		}
		"141860097"
		{
			"npc_dota_hero_alchemist" "hero"
			"models/heroes/alchemist/alchemist.vmdl" "model"
			"models/heroes/alchemist/alchemist_ogre_head.vmdl" "wearable"
			"models/heroes/alchemist/alchemist_goblin_head.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_armor/waaagh_alchemist_armor.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_arms/waaagh_alchemist_arms.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_back/waaagh_alchemist_back.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_neck/waaagh_alchemist_neck.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_off_hand/waaagh_alchemist_off_hand.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_shoulder/waaagh_alchemist_shoulder.vmdl" "wearable"
			"models/items/alchemist/waaagh_alchemist_weapon/waaagh_alchemist_weapon.vmdl" "wearable"
			"models/items/alchemist/midasknuckles/midasknuckles.vmdl" "wearable"
		}

	}
	"elena"
	{
		"english"
		{
			"models/heroes/death_prophet/death_prophet.vmdl" "model"
			"models/items/death_prophet/fatal_blossom_nails/fatal_blossom_nails.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_armor/burial_robes_armor.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_belt/burial_robes_belt.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_legs/burial_robes_legs.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_head/burial_robes_head.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_vortex/burial_robes_vortex.vmdl" "wearable"
		}
		"russian"
		{
			"models/heroes/death_prophet/death_prophet.vmdl" "model"
			"models/items/death_prophet/fatal_blossom_nails/fatal_blossom_nails.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_armor/burial_robes_armor.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_belt/burial_robes_belt.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_legs/burial_robes_legs.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_head/burial_robes_head.vmdl" "wearable"
			"models/items/death_prophet/burial_robes_vortex/burial_robes_vortex.vmdl" "wearable"
		}
				"115096756"
		{ 
"npc_dota_hero_phoenix_alt1" "hero" 
"models/heroes/phoenix/phoenix_bird.vmdl" "model" 
"models/items/phoenix/blazing_wing_fire_wings/blazing_wing_fire_wings.vmdl" "wearable" 
"models/items/phoenix/solar_forge/mesh/solar_forge_model.vmdl" "wearable" 
"models/items/phoenix/blazing_wing_fire_wings/blazing_wing_fire_wings_fx.vmdl" "wearable" 


"particle1" 
{ 
"particle" "particles/econ/items/phoenix/phoenix_solar_forge/phoenix_solar_forge_ambient.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/units/heroes/hero_phoenix/phoenix_ambient.vpcf" 
"attach" "-1" 
} 

}
		
				"148967307"
		{
		"npc_dota_hero_crystal_maiden" "hero" 
"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model" 
"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_head/warden_icewrack_head.vmdl" "wearable" 
"models/items/crystal_maiden/immortal_shoulders/cm_immortal_shoulders.vmdl" "wearable" 
"models/items/crystal_maiden/warden_icewrack_staff/warden_icewrack_staff.vmdl" "wearable" 
"models/items/crystal_maiden/crystalline_empress_arms/crystalline_empress_arms.vmdl" "wearable" 

"particle1" 
{ 
"particle" "particles/maiden_freezing_field_casterribbons_arcana1_custom.vpcf" 
"attach" "-1" 
} 
"particle2" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient.vpcf" 
"attach" "-1" 
} 


"particle5" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_ball_sparks.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_ambient_halo.vpcf" 
"attach" "-1" 
} 
"particle6" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient.vpcf" 
"attach" "-1" 
} 

"particle7" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
} 
"particle8" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_ground_ambient.vpcf" 
"attach" "-1" 
} 
"particle9" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle10" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/crystal_maiden_cowl_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle11" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient.vpcf" 
"attach" "-1" 
} 
"particle12" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_b.vpcf" 
"attach" "-1" 
} 
"particle13" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_c.vpcf" 
"attach" "-1" 
} 
"particle14" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_arcana_base_ambient_d.vpcf" 
"attach" "-1" 
} 
"particle15" 
{ 
"particle" "particles/econ/items/pangolier/pangolier_ti8_immortal/pangolier_ti8_immortal_ambient_hearts.vpcf" 
"attach" "-1" 
} 
"particle16" 
{ 
"particle" "particles/units/heroes/hero_tusk/tusk_frozen_sigil.vpcf" 
"attach" "-1" 
} 

"particle18" 
{ 
"particle" "particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_snow_b_arcana1.vpcf" 
"attach" "-1" 
}
		}

		"54840512"
		{
			"npc_dota_hero_nevermore_alt1" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"291593844"
		{
			"npc_dota_hero_lina_alt1" "hero"
			"models/heroes/lina/lina.vmdl" "model"
			"models/items/lina/lina_immortal_ii/mesh/lina_immortal_ii.vmdl" "wearable"
			"models/items/lina/lina_ti7/lina_ti7.vmdl" "wearable"
			"models/items/lina/origins_flamehair/origins_flamehair.vmdl" "wearable"
			"fiery_soul" "translate"

			"particle1"
			{
				"particle" "particles/econ/items/lina/lina_head_headflame/lina_headflame.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/lina/lina_head_headflame/lina_flame_hand_dual_headflame.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/lina/lina_fire_lotus/lina_fire_lotus_ambient.vpcf"
				"attach" "-1"
			}
		}

		"870553155"
		{
			"npc_dota_hero_legion_commander_alt1" "hero"
			"models/heroes/legion_commander/legion_commander.vmdl" "model"
			"models/items/legion_commander/stonehall_weapon/stonehall_weapon.vmdl" "wearable"
			"models/items/legion_commander/stonehall_shoulder/stonehall_shoulder.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head_alt/stonehall_head_alt.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head/stonehall_head.vmdl" "wearable"
			"models/items/legion_commander/stonehall_back/stonehall_back.vmdl" "wearable"
			"models/items/legion_commander/stonehall_arms/stonehall_arms.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl" "wearable"
			"1" "material_group"
			"1.0" "scale"
			"dualwield" "translate"
		}

		"170281422"
		{
			"npc_dota_hero_techies_alt1" "hero"
			"models/heroes/techies/techies.vmdl" "model"
			"models/heroes/techies/techies_spleen_weapon.vmdl" "wearable"
			"models/items/techies/bigshot/bigshot.vmdl" "wearable"
			"models/items/techies/bigshot/bigshot_barrel.vmdl" "wearable"
			"models/items/techies/bigshot/bigshot_spleen_costume.vmdl" "wearable"
			"models/items/techies/bigshot/bigshot_squee_costume.vmdl" "wearable"
		}

		"99888925"
		{
			"npc_dota_hero_nevermore" "hero"
			"models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl" "model"
			"models/items/nevermore/diabolical_fiend_arms/diabolical_fiend_arms.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_head/diabolical_fiend_head.vmdl" "wearable"
			"models/items/nevermore/diabolical_fiend_shoulder/diabolical_fiend_shoulder.vmdl" "wearable"
			"particle1"
			{
				"particle" "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_ambient.vpcf"
				"attach" "-1"
			}
		}

		"99707924"
		{
			"npc_dota_hero_templar_assassin" "hero"
			"models/heroes/lanaya/lanaya.vmdl" "model"
			"models/items/lanaya/heavenly_secrets_armor/heavenly_secrets_armor.vmdl" "wearable"
			"models/items/lanaya/heavenly_secrets_head/heavenly_secrets_head.vmdl" "wearable"
			"models/items/lanaya/heavenly_secrets_shoulder/heavenly_secrets_shoulder.vmdl" "wearable"
			"models/items/templar_assassin/psi_blades/psi_blades_immortal.vmdl" "wearable"
		}

		"849777283" 
		{
			"npc_dota_hero_drow_ranger" "hero"
			"models/heroes/drow/drow.vmdl" "model"
			"models/items/drow/boots_of_the_envious_archer/boots_of_the_envious_archer.vmdl" "wearable"
			"models/items/drow/bow_of_the_envious_archer/bow_of_the_envious_archer.vmdl" "wearable"
			"models/items/drow/bracers_of_the_envious_archer/bracers_of_the_envious_archer.vmdl" "wearable"
			"models/items/drow/guards_of_the_envious_archer/guards_of_the_envious_archer.vmdl" "wearable"
			"models/items/drow/mask_of_the_envious_archer/mask_of_the_envious_archer.vmdl" "wearable"
			"models/items/drow/quiver_of_the_envious_archer/quiver_of_the_envious_archer.vmdl" "wearable"
			"models/items/drow/ti6_immortal_cape/mesh/drow_ti6_immortal_cape.vmdl" "wearable"
		}

		"126162950"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"55428680"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"114178619"
		{
			"npc_dota_hero_terrorblade" "hero"
			"models/heroes/terrorblade/terrorblade.vmdl" "model"
			"models/items/terrorblade/endless_purgatory_head/endless_purgatory_head.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_weapon/endless_purgatory_weapon.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_armor/endless_purgatory_armor.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"models/items/terrorblade/endless_purgatory_back/endless_purgatory_back.vmdl" "wearable"
			"particle1" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_body_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle3" 
			{
				"particle" "particles/econ/items/terrorblade/terrorblade_horns_arcana/terrorblade_ambient_eyes_arcana_horns.vpcf"
				"attach" "-1"
			}
			"particle4" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade.vpcf"
				"attach" "-1"
			}
			"particle5" 
			{
				"particle" "particles/units/heroes/hero_terrorblade/terrorblade_ambient_sword_blade_2.vpcf"
				"attach" "-1"
			}
			"color" 
			{
				"cp" "15"
				"1" "255"
				"2" "0"
				"3" "0"
			}
		}

		"436851017" 
		{
			"npc_dota_hero_templar_assassin" "hero"
			"models/heroes/lanaya/lanaya.vmdl" "model"
			"models/items/lanaya/heavenly_secrets_armor/heavenly_secrets_armor.vmdl" "wearable"
			"models/items/lanaya/heavenly_secrets_head/heavenly_secrets_head.vmdl" "wearable"
			"models/items/lanaya/heavenly_secrets_shoulder/heavenly_secrets_shoulder.vmdl" "wearable"
			"models/items/templar_assassin/psi_blades/psi_blades_immortal.vmdl" "wearable"
		}

		"105773141"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_armor/tarrasque_scale_armor.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_arms/tarrasque_scale_arms.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_belt/tarrasque_scale_belt.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_head/tarrasque_scale_head.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_shoulder/tarrasque_scale_shoulder.vmdl" "wearable"
			"petri_petrosyan_flat_joke"
			{
				"anim" "ACT_DOTA_ATTACK_EVENT_BASH"
				"translate" "basher"
				"sound" "Hero_Antimage.ManaBreak"
			}
		}

		"289413364"
		{
			"npc_dota_hero_lich" "hero"
			"models/heroes/lich/lich.vmdl" "model"
			"models/items/lich/blizzard_tyrant_arms/blizzard_tyrant_arms.vmdl" "wearable"
			"models/items/lich/blizzard_tyrant_belt/blizzard_tyrant_belt.vmdl" "wearable"
			"models/items/lich/blizzard_tyrant_head/blizzard_tyrant_head.vmdl" "wearable"
			"models/items/lich/blizzard_tyrant_neck/blizzard_tyrant_neck.vmdl" "wearable"
			"models/heroes/lich/lich_horns.vmdl" "wearable"
		}

		"427341314"
		{
			"npc_dota_hero_night_stalker" "hero"
			"models/heroes/nightstalker/nightstalker.vmdl" "model"
			"models/items/nightstalker/evil_eyednightstalker_arms/evil_eyednightstalker_arms.vmdl" "wearable"
			"models/items/nightstalker/evil_eyednightstalker_back/evil_eyednightstalker_back.vmdl" "wearable"
			"models/items/nightstalker/evil_eyednightstalker_head/evil_eyednightstalker_head.vmdl" "wearable"
			"models/items/nightstalker/evil_eyednightstalker_legs/evil_eyednightstalker_legs.vmdl" "wearable"
			"models/items/nightstalker/evil_eyednightstalker_tail/evil_eyednightstalker_tail.vmdl" "wearable"
		}

		"199846592"
		{
			"npc_dota_hero_broodmother" "hero"
			"models/heroes/broodmother/broodmother.vmdl" "broodmother"
			"models/items/broodmother/abdomen_of_perception/abdomen_of_perception.vmdl" "wearable"
			"models/items/broodmother/crown_of_perception/crown_of_perception.vmdl" "wearable"
			"models/items/broodmother/legs_of_perception/legs_of_perception.vmdl" "wearable"
		}

		"421647980"
		{
			"npc_dota_hero_mirana" "hero"
			"models/heroes/mirana/mirana.vmdl" "model"
			"models/items/mirana/sl_cat/sl_cat.vmdl" "wearable"
			"models/items/mirana/sl_cape/sl_cape.vmdl" "wearable"
			"models/items/mirana/sl_head/sl_head.vmdl" "wearable"
			"models/items/mirana/sl_quiver/sl_quiver.vmdl" "wearable"
			"models/items/mirana/sl_shoulder/sl_shoulder.vmdl" "wearable"
		}

		"164268113"
		{
			"npc_dota_hero_spectre" "hero"
			"models/heroes/spectre/spectre.vmdl" "model"
			"models/items/spectre/entropy_belt/entropy_belt.vmdl" "wearable"
			"models/items/spectre/entropy_head/entropy_head.vmdl" "wearable"
			"models/items/spectre/entropy_misc/entropy_misc.vmdl" "wearable"
			"models/items/spectre/entropy_shoulders/entropy_shoulders.vmdl" "wearable"
			"models/items/spectre/entropy_weapon/entropy_weapon.vmdl" "wearable"
		}

		"115842333"
		{
			"npc_dota_hero_nyx_assassin" "hero"
			"models/heroes/nerubian_assassin/nerubian_assassin.vmdl" "model"
			"models/items/nerubian_assassin/artificial_metamorphosis_back/artificial_metamorphosis_back.vmdl" "wearable"
			"models/items/nerubian_assassin/artificial_metamorphosis_head/artificial_metamorphosis_head.vmdl" "wearable"
			"models/items/nerubian_assassin/artificial_metamorphosis_misc/artificial_metamorphosis_misc.vmdl" "wearable"
			"models/items/nerubian_assassin/artificial_metamorphosis_weapon/artificial_metamorphosis_weapon.vmdl" "wearable"
		}
		"234197909"
		{
			"npc_dota_hero_spectre" "hero"
			"models/heroes/spectre/spectre.vmdl" "model"
			"models/items/spectre/entropy_belt/entropy_belt.vmdl" "wearable"
			"models/items/spectre/entropy_head/entropy_head.vmdl" "wearable"
			"models/items/spectre/entropy_misc/entropy_misc.vmdl" "wearable"
			"models/items/spectre/entropy_shoulders/entropy_shoulders.vmdl" "wearable"
			"models/items/spectre/entropy_weapon/entropy_weapon.vmdl" "wearable"
		}
		"208624781"
		{
			
			"npc_dota_hero_lycan" "hero"
			"models/items/lycan/ultimate/alpha_trueform9/alpha_trueform9.vmdl" "model"
			"models/items/enchantress/enchantress_crown.vmdl" "wearable"
		}
		"80161021"
		{
			"npc_dota_hero_antimage" "hero"
			"models/heroes/antimage/antimage.vmdl" "model"
			"models/items/antimage/skullbasher/skullbasher_gold.vmdl" "wearable"
			"models/items/antimage/skullbasher/skullbasher_gold_offhand.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_armor/tarrasque_scale_armor.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_arms/tarrasque_scale_arms.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_belt/tarrasque_scale_belt.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_head/tarrasque_scale_head.vmdl" "wearable"
			"models/items/antimage/tarrasque_scale_shoulder/tarrasque_scale_shoulder.vmdl" "wearable"
			"petri_petrosyan_flat_joke"
			{
				"anim" "ACT_DOTA_ATTACK_EVENT_BASH"
				"translate" "basher"
				"sound" "Hero_Antimage.ManaBreak"
			}
		}
		"213808733"
		{
			"npc_dota_hero_crystal_maiden" "hero"
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable"
			"models/heroes/crystal_maiden/head_item.vmdl" "wearable"
			"models/heroes/crystal_maiden/crystal_maiden_shoulders.vmdl" "wearable"
			"models/heroes/crystal_maiden/crystal_maiden_staff.vmdl" "wearable"
		}
		"61750908"
		{
			"models/heroes/kunkka/kunkka.vmdl" "model"
			"models/items/kunkka/inquisitor_tide_back/inquisitor_tide_back.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_belt/inquisitor_tide_belt.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_glove/inquisitor_tide_glove.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_head/inquisitor_tide_head.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_legs/inquisitor_tide_legs.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_misc/inquisitor_tide_misc.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_shoulder/inquisitor_tide_shoulder.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_weapon/inquisitor_tide_weapon.vmdl" "wearable"
		}
		"229973029"
		{
			"npc_dota_hero_dazzle" "hero"
			"models/heroes/dazzle/dazzle.vmdl" "model"
			"models/items/dazzle/darkclaw_acolyte_arms/darkclaw_acolyte_arms.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_back/darkclaw_acolyte_back.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_legs/darkclaw_acolyte_legs.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/darkclaw_acolyte_misc.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_misc/mesh/dazzle_darkclaw_acolyte_claw.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/darkclaw_acolyte_weapon.vmdl" "wearable"
			"models/items/dazzle/darkclaw_acolyte_weapon/mesh/darkclaw_acolyte_claw_fx.vmdl" "wearable"
		}
		"177714054"
		{
			"npc_dota_hero_kunkka" "hero"
			"models/heroes/kunkka/kunkka.vmdl" "model"
			"models/items/kunkka/inquisitor_tide_back/inquisitor_tide_back.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_belt/inquisitor_tide_belt.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_glove/inquisitor_tide_glove.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_head/inquisitor_tide_head.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_legs/inquisitor_tide_legs.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_misc/inquisitor_tide_misc.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_shoulder/inquisitor_tide_shoulder.vmdl" "wearable"
			"models/items/kunkka/inquisitor_tide_weapon/inquisitor_tide_weapon.vmdl" "wearable"
		}
		"282108122" 
		{
			"npc_dota_hero_lone_druid" "hero"
			"models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl" "model"
		}
		"345384755"
		{
			"npc_dota_hero_queenofpain" "hero"
			"models/heroes/queenofpain/queenofpain.vmdl" "model"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_back/dotapit_s3_abyssal_temptress_back.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_head/dotapit_s3_abyssal_temptress_head.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_shoulder/dotapit_s3_abyssal_temptress_shoulder.vmdl" "wearable"
			"models/items/queenofpain/dotapit_s3_abyssal_temptress_weapon/dotapit_s3_abyssal_temptress_weapon.vmdl" "wearable"
		}
		"96034076"
		{
			"npc_dota_hero_crystal_maiden" "hero"
			"models/heroes/crystal_maiden/crystal_maiden_arcana.vmdl" "model"
			"models/heroes/crystal_maiden/crystal_maiden_arcana_back.vmdl" "wearable"
			"models/heroes/crystal_maiden/head_item.vmdl" "wearable"
			"models/heroes/crystal_maiden/crystal_maiden_shoulders.vmdl" "wearable"
			"models/heroes/crystal_maiden/crystal_maiden_staff.vmdl" "wearable"
		}
		"141860097"
		{
			"npc_dota_hero_lina_alt1" "hero"
			"models/heroes/lina/lina.vmdl" "model"
			"models/items/lina/lina_immortal_ii/mesh/lina_immortal_ii.vmdl" "wearable"
			"models/items/lina/lina_ti7/lina_ti7.vmdl" "wearable"
			"models/items/lina/origins_flamehair/origins_flamehair.vmdl" "wearable"
			"fiery_soul" "translate"

			"particle1"
			{
				"particle" "particles/econ/items/lina/lina_head_headflame/lina_headflame.vpcf"
				"attach" "-1"
			}
			"particle2"
			{
				"particle" "particles/econ/items/lina/lina_head_headflame/lina_flame_hand_dual_headflame.vpcf"
				"attach" "-1"
			}
			"particle3"
			{
				"particle" "particles/econ/items/lina/lina_fire_lotus/lina_fire_lotus_ambient.vpcf"
				"attach" "-1"
			}
		}
	}
	"miniactors"
	{
		"english"
		{
			"models/heroes/storm_spirit/storm_spirit.vmdl" "model"
			"models/items/storm_spirit/raikage_ares_armor/raikage_ares_armor.vmdl" "wearable"
			"models/items/storm_spirit/raikage_ares_arms/raikage_ares_arms.vmdl" "wearable"
			"models/items/storm_spirit/raikage_ares_head/raikage_ares_head.vmdl" "wearable"
		}
		"russian"
		{
			"models/heroes/storm_spirit/storm_spirit.vmdl" "model"
			"models/items/storm_spirit/raikage_ares_armor/raikage_ares_armor.vmdl" "wearable"
			"models/items/storm_spirit/raikage_ares_arms/raikage_ares_arms.vmdl" "wearable"
			"models/items/storm_spirit/raikage_ares_head/raikage_ares_head.vmdl" "wearable"
		}
		"199846592"
		{
			"npc_dota_hero_silencer" "hero"
			"models/heroes/silencer/silencer.vmdl" "model"
			"models/items/silencer/silent_guardian_arms/silent_guardian_arms.vmdl" "wearable"			
			"models/items/silencer/silent_guardian_belt/silent_guardian_belt.vmdl" "wearable"	
			"models/items/silencer/silent_guardian_head/silent_guardian_head.vmdl" "wearable"	
			"models/items/silencer/silent_guardian_off_hand/silent_guardian_off_hand.vmdl" "wearable"	
			"models/items/silencer/silent_guardian_shoulder/silent_guardian_shoulder.vmdl" "wearable"	
			"models/items/silencer/silent_guardian_weapon/silent_guardian_weapon.vmdl" "wearable"	
		}
		"96034076" 
		{
			"models/heroes/juggernaut/juggernaut.vmdl" "model"
			"models/items/juggernaut/armor_for_the_favorite_arms/armor_for_the_favorite_arms.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_back/armor_for_the_favorite_back.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_head/armor_for_the_favorite_head.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_legs/armor_for_the_favorite_legs.vmdl" "wearable"
			"models/items/juggernaut/armor_for_the_favorite_weapon/armor_for_the_favorite_weapon.vmdl" "wearable"
		}
		"147518249"
		{
			"models/heroes/legion_commander/legion_commander.vmdl" "model"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_shoulder.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_head.vmdl" "wearable"
			"models/items/legion_commander/stonehall_head/stonehall_head.vmdl" "wearable"
			"models/items/legion_commander/legacy_of_the_fallen_legion/legacy_of_the_fallen_legion.vmdl" "wearable"
			"models/items/legion_commander/stonehall_arms/stonehall_arms.vmdl" "wearable"
			"models/items/legion_commander/legion_commander_ti8/legion_commander_ti8_legs.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl" "wearable"
			"models/items/legion_commander/demon_sword.vmdl_mg" "1"
			"particle1"
			{
				"particle" "particles/econ/items/legion/legion_fallen/legion_fallen_ambient.vpcf"
				"attach" "-1"
			}
			"1" "material_group"
			"1.0" "scale"
			"dualwield" "translate"
		}
	}
}