"walls"
{
	"npc_petri_wall"
	{
		"1"
		{
			"model"
			{
				"models/props_debris/merchant_debris_chest002.vmdl" "model"
			}
			"scale"	"0.6"
		}
		"2"
		{
			"model"
			{
				"models/props_items/hyperstone.vmdl" "model"
			}
			"scale"	"3.0"
		}
		"3"
		{
			"model"
			{
				"models/props_items/powertreads.vmdl" "model"
			}
			"scale"	"2.5"
		}
		"4"
		{
			"model"
			{
				"models/heroes/bounty_hunter/bounty_hunter.vmdl" "model"
			}
			"scale"	"1.1"
		}
		"5"
		{
			"model"
			{
				"models/heroes/windrunner/windrunner.vmdl" "model"
			}
			"scale"	"1.5"
		}
		"6"
		{
			"model"
			{
				"maps/cavern_assets/models/crystals/crystal03.vmdl" "model"
			}
			"scale"	"1.0"
		}
		"7"
		{
			"model"
			{
				"models/creeps/neutral_creeps/n_creep_ancient_frog/n_creep_ancient_frog.vmdl" "model"
			}
			"scale"	"1.8"
		}
		"8"
		{
			"model"
			{
				"models/creeps/neutral_creeps/n_creep_satyr_spawn_a/n_creep_satyr_spawn_a.vmdl" "model"
			}
			"scale"	"1.8"
		}
		"9"
		{
			"model"
			{
				"models/heroes/techies/fx_techies_remotebomb.vmdl" "model"
			}
			"scale"	"3.0"
		}
 		"10"
		{
			"model"
			{
				"models/heroes/lycan/lycan_wolf_rubick.vmdl" "model"
			}
			"scale"	"1.7"
		}
		"11"
		{
			"model"
			{
				"models/props_gameplay/divine_rapier.vmdl" "model"
			}
			"scale"	"4.0"
		}
		"12"
		{
			"model"
			{
				"models/creeps/roshan/aegis.vmdl" "model"
			}
			"scale"	"2.05"
			"zOffset" "96"
			"angles"
			{
				"x" "-19"
				"y" "-45"
				"z"	"-28"
			}
		}
	}
	"npc_petri_earth_wall"
	{
		"1"
		{
			"model"
			{
				"models/heroes/brewmaster/brewmaster_earthspirit.vmdl" "model"
			}
			"scale"	"0.95"
		}
		"2"
		{
			"model"
			{
				"models/heroes/brewmaster/brewmaster_earthspirit.vmdl" "model"
			}
			"scale"	"1.0"
		}
		"3"
		{
			"model"
			{
				"models/heroes/brewmaster/brewmaster_earthspirit.vmdl" "model"
			}
			"scale"	"1.05"
		}
		"4"
		{
			"model"
			{
				"models/heroes/brewmaster/brewmaster_earthspirit.vmdl" "model"
			}
			"scale"	"1.1"
		}
		"5"
		{
			"model"
			{
				"models/heroes/brewmaster/brewmaster_earthspirit.vmdl" "model"
			}
			"scale"	"1.15"
		}
		"6"
		{
			"model"
			{
				"models/heroes/brewmaster/brewmaster_earthspirit.vmdl" "model"
			}
			"scale"	"1.2"
		}
		"7"
		{
			"model"
			{
				"models/heroes/earthshaker/earthshaker.vmdl" "model"
			}
			"scale"	"1.25"
		}
		"8"
		{
			"model"
			{
				"models/heroes/earthshaker/earthshaker.vmdl" "model"
			}
			"scale"	"1.3"
		}
		"9"
		{
			"model"
			{
				"models/heroes/earthshaker/earthshaker_memorial.vmdl" "model"
			}
			"scale"	"1.35"
		}
		"10"
		{
			"model"
			{
				"models/earthwall/earthwall.vmdl" "model"
			}
			"scale"	"1.4"
		}
		"11"
		{
			"model"
			{
				"models/earthwall/earthwall.vmdl" "model"
			}
			"scale"	"1.45"
		}
		"12"
		{
			"model"
			{
				"models/heroes/elder_titan/elder_titan.vmdl" "model"
			}
			"scale"	"1.5"
		}
	}
}